from __future__ import annotations

from .ball_compensation import BallCompensationModel
from .ball_compensation_checkpoint import (
    BallCompensationCheckpoint,
    HoldoutCheckpointObservation,
    ball_compensation_checkpoint_compatibility_errors,
    delete_ball_compensation_checkpoint,
    load_ball_compensation_checkpoint,
    make_ball_compensation_checkpoint,
    restart_ball_compensation_checkpoint_from_holdout,
    save_ball_compensation_checkpoint,
)
from .ball_compensation_diagnostics import (
    ReusableHoldoutSource,
    ReusedHoldoutDiagnostic,
    evaluate_ball_compensation_training_residuals,
    fit_with_reused_holdout_diagnostic,
    load_reusable_holdout_source,
)
from .audit import CalibrationAudit, load_calibration_audit_summaries, start_calibration_audit
from .ball_compensation_sampling import (
    BallCompensationSample,
    BallCompensationValidationError,
    MIN_BALL_COMPENSATION_ACCEPTED_SAMPLES,
    MIN_BALL_COMPENSATION_HOLDOUT_SAMPLES,
    MIN_BALL_COMPENSATION_TRAINING_SAMPLES,
    ValidatedBallCompensation,
    aggregate_ball_compensation_holdout_repeats,
    ball_compensation_sample_from_dict,
    ball_compensation_sample_weights,
    ball_holdout_geometry_is_formal,
    build_ball_compensation_model,
    build_engineered_ball_sampling_grid,
    evaluate_ball_compensation_holdout,
    fit_and_validate_ball_compensation,
    select_ball_compensation_holdout_targets,
    split_ball_compensation_samples,
    update_calibration_table_boundaries_from_geometry_frame,
)
from .ball_compensation_resampling import (
    BallCompensationTrainingSource,
    FailedHoldoutRecoveryPlan,
    HighResidualTrainingResamplePlan,
    HighResidualTrainingResamplingTask,
    HoldoutRepeatabilityAssessment,
    LocationRepeatability,
    aggregate_training_repeats,
    assess_holdout_repeatability,
    load_ball_compensation_training_source,
    plan_failed_holdout_recovery,
    plan_high_residual_training_resampling,
    prepare_high_residual_training_resampling,
)
from .camera import CameraCalibration
from .geometry import CalibrationUnavailableError, IndependentGeometry, ProjectedEllipse
from .linked import (
    MIN_LINKED_PATTERN_MATCHED_POINTS,
    LinkedCalibrationObservation,
    LinkedCalibrationPattern,
    LinkedCalibrationResult,
    LinkedPatternCaptureResult,
    build_linked_patterns,
    collect_linked_pattern_observation,
    linked_calibration_runtime_summary,
    linked_table_surface_polygon,
    match_linked_pattern_observation,
    projection_output_summary,
    solve_linked_projection_calibration,
)
from .projector import ProjectionCalibration
from .service import (
    CalibrationService,
    create_calibration_service,
    create_setting_aware_calibration_service,
)
from .verification import format_holdout_report, verify_holdout_file, verify_holdout_samples

__all__ = [
    "BallCompensationModel",
    "BallCompensationCheckpoint",
    "HoldoutCheckpointObservation",
    "ball_compensation_checkpoint_compatibility_errors",
    "delete_ball_compensation_checkpoint",
    "load_ball_compensation_checkpoint",
    "make_ball_compensation_checkpoint",
    "restart_ball_compensation_checkpoint_from_holdout",
    "save_ball_compensation_checkpoint",
    "ReusableHoldoutSource",
    "ReusedHoldoutDiagnostic",
    "evaluate_ball_compensation_training_residuals",
    "fit_with_reused_holdout_diagnostic",
    "load_reusable_holdout_source",
    "CalibrationAudit",
    "load_calibration_audit_summaries",
    "start_calibration_audit",
    "BallCompensationSample",
    "BallCompensationValidationError",
    "MIN_BALL_COMPENSATION_ACCEPTED_SAMPLES",
    "MIN_BALL_COMPENSATION_HOLDOUT_SAMPLES",
    "MIN_BALL_COMPENSATION_TRAINING_SAMPLES",
    "ValidatedBallCompensation",
    "aggregate_ball_compensation_holdout_repeats",
    "ball_compensation_sample_from_dict",
    "ball_compensation_sample_weights",
    "aggregate_training_repeats",
    "assess_holdout_repeatability",
    "ball_holdout_geometry_is_formal",
    "CameraCalibration",
    "IndependentGeometry",
    "ProjectedEllipse",
    "CalibrationUnavailableError",
    "ProjectionCalibration",
    "CalibrationService",
    "create_calibration_service",
    "create_setting_aware_calibration_service",
    "build_ball_compensation_model",
    "build_engineered_ball_sampling_grid",
    "evaluate_ball_compensation_holdout",
    "fit_and_validate_ball_compensation",
    "FailedHoldoutRecoveryPlan",
    "BallCompensationTrainingSource",
    "HighResidualTrainingResamplePlan",
    "HighResidualTrainingResamplingTask",
    "HoldoutRepeatabilityAssessment",
    "LocationRepeatability",
    "plan_failed_holdout_recovery",
    "load_ball_compensation_training_source",
    "plan_high_residual_training_resampling",
    "prepare_high_residual_training_resampling",
    "select_ball_compensation_holdout_targets",
    "split_ball_compensation_samples",
    "update_calibration_table_boundaries_from_geometry_frame",
    "LinkedCalibrationPattern",
    "MIN_LINKED_PATTERN_MATCHED_POINTS",
    "LinkedCalibrationObservation",
    "LinkedCalibrationResult",
    "LinkedPatternCaptureResult",
    "build_linked_patterns",
    "collect_linked_pattern_observation",
    "linked_calibration_runtime_summary",
    "linked_table_surface_polygon",
    "match_linked_pattern_observation",
    "solve_linked_projection_calibration",
    "projection_output_summary",
    "format_holdout_report",
    "verify_holdout_file",
    "verify_holdout_samples",
]
